version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gym_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
